CREATE TABLE [PACIENTE].[UBIGEO]
(
[CODUB] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DISTUB] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROVUB] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPUB] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [PACIENTE].[UBIGEO] ADD CONSTRAINT [PK_CODUB] PRIMARY KEY CLUSTERED  ([CODUB]) ON [PRIMARY]
GO
